apiVersion: v1
kind: Pod
metadata:
  Name: openlmis
  labels:
    name: lmis
    app: iohie
    component: lmis
spec:
  hostname: lmis
  subdomain: iohie
  containers:
  - image: openlmis:3.5.0
    name: openlmis
  - image: pcmt:3.5.0
    name: pcmt
---
